name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  check_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync source code to server
        uses: appleboy/rsync-action@latest # 또는 최신 버전 번호
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./
          target: /home/kimtg-proejct/${{ github.event.repository.name }}
          delete: true
          args: -avz
      - name: Sync source code to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }} 
          script: |                       
            echo "SSH connection successful!"  # 연결이 성공하면 출력
