name: Deploy Vue App

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./"  # 리포지토리의 모든 파일을 선택
          target: "/var/www/vue-simple-board"  # 서버의 대상 폴더
          rm: true  # 기존 파일을 덮어쓰고 새 파일을 전송

      - name: Set permissions on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo chown -R www-data:www-data /var/www/vue-simple-board
            sudo chmod -R 755 /var/www/vue-simple-board
