name: Deploy Vue App

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 트리거를 위한 이벤트 추가


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}          
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf /var/www/vue-simple-board/*
            cp -r dist/* /var/www/vue-simple-board/
