name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  check_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync source code to server
        uses: burnett0/rsync-deployments@5.2
        with:
          ssh_key: ${{ secrets.SERVER_KEY }}
          args: -avz --delete
          path: ./
          remote_path: ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/kimtg-proejct/${{ github.event.repository.name }}
      - name: Sync source code to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }} 
          script: |                       
            echo "SSH connection successful!"  # 연결이 성공하면 출력
