name: Deploy Vue App

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Check if dist folder exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist folder not found!";
            exit 1;
          fi

      - name: Compress build files
        run: tar -czvf /tmp/vue-app.tar.gz dist/

      - name: SCP file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "/tmp/vue-app.tar.gz"
          target: "/tmp"

      - name: Deploy and extract on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p /var/www/vue-simple-board
            tar -xzvf /tmp/vue-app.tar.gz -C /var/www/vue-simple-board --strip-components=1
            rm -f /tmp/vue-app.tar.gz
