name: Check Server Connection

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  check_connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH connection to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf /home/${{ secrets.SERVER_USER }}/kimtg-project/${{ github.event.repository.name }}
            mkdir /home/${{ secrets.SERVER_USER }}/kimtg-project/${{ github.event.repository.name }}
            echo "SSH connection successful!"  # 연결이 성공하면 출력
