name: Deploy Vue App

on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 트리거를 위한 이벤트 추가


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: |
          npm run build
          ls -al dist

      - name: Cache build files
        uses: actions/cache@v3
        with:
          path: dist
          key: vue-build-${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}          
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm -rf /var/www/vue-simple-board/*
            rsync -avz dist/ /var/www/vue-simple-board/
      - name: Debug SSH Connection
        run: ssh -vvv -i ~/.ssh/id_rsa -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} exit
      
